on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Go Binaries
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Binaries
        uses: ./github/workflows/
        with:
          binary-name: ask
          packages: github.com/andyantrim/ask
          version: '1.0.0'
          extra-package-files: README.md LICENCE
